[mgr]
show_hidden    = false
show_symlink   = true
sort_by        = "natural"
sort_dir_first = true

[preview]
max_width  = 1000
max_height = 1000

[opener]
edit = [
  { run = 'hx "$@"', block = true, desc = "Helix" }
]

[open]
rules = [
  { mime = "text/*",        use = ["edit"] },
  { mime = "application/*", use = ["edit"] },
  { mime = "inode/x-empty", use = ["edit"] },
]

# git.yazi fetchers
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
