#!/usr/bin/env bash

# bash_profile

update_terminal_cwd() {
    # Identify the directory using a "file:" scheme URL,
    # including the host name to disambiguate local vs.
    # remote connections. Percent-escape spaces.
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
}

# Load Autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Set shell
set_shell() {
    STD_SHELLS_CONFIG="/etc/shells"
    BREW_BASH_PATH="$(brew --prefix)/bin/bash"
    if [ ! -z $(grep $STD_SHELLS_CONFIG $BREW_BASH_PATH) ]; then
        echo "$BREW_BASH_PATH not set in $STD_SHELLS_CONFIG"
        sudo -v
        echo $BREW_BASH_PATH | sudo tee -a $STD_SHELLS_CONFIG
        sudo chsh -s $BREW_BASH_PATH $(whoami)
    fi
}

set_shell
unset set_shell

# Load dotfiles
load_dotfiles() {
    declare -a files=(
        $HOME/.dotfiles/shell/bash_options
        $HOME/.dotfiles/shell/bash_exports
        $HOME/.dotfiles/shell/bash_aliases
        $HOME/.dotfiles/shell/functions/*
        $HOME/.dotfiles/shell/bash_prompt
        $HOME/.dotfiles/shell/bash_paths
        $(brew --prefix)/share/bash-completion/bash_completion
        $HOME/.bash_profile.local
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
