#!/bin/bash

# bash_profile

load_dotfiles() {
    declare -a files=(
        $HOME/.dotfiles/shell/bash_options
        $HOME/.dotfiles/shell/bash_exports
        $HOME/.dotfiles/shell/bash_aliases
        $HOME/.dotfiles/shell/functions/*
        $HOME/.dotfiles/shell/bash_prompt
        $HOME/.dotfiles/shell/bash_paths
        $(brew --prefix)/etc/bash_completion
        $HOME/.bash_profile.local
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
