#!/usr/bin/env zsh

###
#
#           Settings by  : Per Töyrä
#           Adopted from : La Clémentine · https://medium.com/@laclementine/
#           Tested with  : macOS Sequoia 15.0
#
###

echo "Setting macOS defaults..."

# Get current Username and User ID
CURRENT_USER=$(stat -f %Su /dev/console)
USER_ID=$(id -u "$CURRENT_USER")


############
# MENU BAR #
############

# Show bluetooth icon
sudo -u "$CURRENT_USER" defaults -currentHost write com.apple.controlcenter Bluetooth -int 18

# Show volume icon
sudo -u "$CURRENT_USER" defaults -currentHost write com.apple.controlcenter Sound -int 18


##########
# FINDER #
##########

# New Finder windows points to home
sudo -u "$CURRENT_USER" defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Disable the warning when changing a file extension
sudo -u "$CURRENT_USER" defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Expand print panel by default
sudo -u "$CURRENT_USER" defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
sudo -u "$CURRENT_USER" defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Avoid creating .DS_Store files on network or USB volumes
sudo -u "$CURRENT_USER" defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
sudo -u "$CURRENT_USER" defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Disable recent apps in Dock
launchctl asuser "$USER_ID" sudo -u "$CURRENT_USER" defaults write com.apple.dock show-recents -int 0


############
# KEYBOARD #
############

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Use function keys as F-keys by default and not media keys
defaults write -g com.apple.keyboard.fnState -bool true

# Disable add full stop with double-space
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

###################
# SYSTEM SETTINGS #
###################

# Beep feedback when changing volume
sudo -u "$CURRENT_USER" defaults write NSGlobalDomain com.apple.sound.beep.feedback -integer 1

# Beep feedback when plugging in the power adapter
sudo -u "$CURRENT_USER" defaults write com.apple.PowerChime ChimeOnAllHardware -bool true

# Prevent Time Machine from prompting to use new hard drives as backup volume
sudo -u "$CURRENT_USER" defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Expand save panel by default
sudo -u "$CURRENT_USER" defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Enable two buttons / secondary / right click on Magic Mouses
sudo -u "$CURRENT_USER" defaults write com.apple.AppleMultitouchMouse MouseButtonMode -string "TwoButton"
sudo -u "$CURRENT_USER" defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode -string "TwoButton"

# Prevent Photos.app from opening when a device is plugged
sudo -u "$CURRENT_USER" defaults write com.apple.ImageCapture disableHotPlug -bool yes

# Uncheck 'Reopen Windows When Logging Back'
sudo -u "$CURRENT_USER" defaults write com.apple.loginwindow TALLogoutSavesState -bool false

# Enable automatic updates
#defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist AutomaticallyInstallMacOSUpdates -bool true
#defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist AutomaticCheckEnabled -bool true
#defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist AutomaticDownload -bool true
#defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist CriticalUpdateInstall -bool true
#defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist ConfigDataInstall -bool true
#defaults write /Library/Preferences/com.apple.commerce.plist AutoUpdate -bool true

# Enable location services
#defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -int 1
#killall locationd
#launchctl kickstart -k system/com.apple.locationd

# Enable Firewall
#/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
#/usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

# Disable Power Nap & Wake for Network Access
#pmset -a powernap 0
#pmset -a womp 0


############
# TERMINAL #
############

# Enable Secure Keyboard Entry in Terminal.app
# See: https://security.stackexchange.com/a/47786/8918
defaults write com.apple.terminal SecureKeyboardEntry -bool true

# Touch ID for sudo commands in Terminal · Sonoma + Sequoia
CHECK_3RD_ROW=$(cat /private/etc/pam.d/sudo_local 2>/dev/null | sed -n 3p)
if [ "$CHECK_3RD_ROW" = "auth       sufficient     pam_tid.so" ]; then
    echo "Sudo Touch ID is already configured."
else
    sudo cp /private/etc/pam.d/sudo_local.template /private/etc/pam.d/sudo_local
    sudo sed -i '.bak' '3s/#//' "/private/etc/pam.d/sudo_local"
    echo "Sudo Touch ID is now configured."
fi


##################
# DESKTOP & DOCK #
##################

# Do not rearrange Spaces based on most recent used
defaults write com.apple.dock mru-spaces -bool false

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen

# Top left screen corner → Mission Control
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0

# Top right screen corner → Desktop
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0


####################
# RESTART SERVICES #
####################

echo "Restarting services..."
echo "✅ Completed!"

killall cfprefsd
killall SystemUIServer
killall Finder
killall Dock
killall TextInputMenuAgent
killall WindowManager
killall replayd

exit 0
