#!/bin/bash

run_atom() {

    if ! type_exists 'atom'; then
        e_error "Atom editor not installed, exiting..."
        exit
    fi

    if ! type_exists 'apm'; then
        e_error "Atom package manager not found, exiting..."
        exit
    fi

    # Copy Atom configuration
    cp -f configs/atom/config.cson \
          configs/atom/init.coffee \
          configs/atom/keymap.cson \
          configs/atom/snippets.cson \
          configs/atom/styles.less \
          ~/.atom

    # List packages to be installed
    local packages=(
        emmet
        minimap
        merge-conflicts
        color-picker
        linter
        linter-jshint
        linter-scss-lint
        linter-less
        linter-csslint
        linter-xmllint
        editorconfig
        xml-formatter
        solarized-dark-ui
    )

    # Install Atom packages
    e_header "Installing Atom packages..."
    apm install ${packages[@]}

    [[ $? ]] && e_success "Done"

    # Cleanup
    apm clean
}
