#!/bin/bash

run_atom() {

    if ! type_exists 'atom'; then
        e_error "Atom editor not installed, exiting..."
        exit
    fi

    if ! type_exists 'apm'; then
        e_error "Atom package manager not found, exiting..."
        exit
    fi

    e_header "Updating Atom packages..."
    # Use the latest version of Homebrew
    apm update
    [[ $? ]] && e_success "Done"

    e_header "Updating any existing Atom packages..."
    # Upgrade any already-installed formulae
    apm upgrade
    [[ $? ]] && e_success "Done"

    e_header "Copying Atom configuration..."
    # Copy Atom configuration
    cp -f configs/atom/config.cson \
          configs/atom/init.coffee \
          configs/atom/keymap.cson \
          configs/atom/snippets.cson \
          configs/atom/styles.less \
          ~/.atom

    [[ $? ]] && e_success "Done"

    e_header "Checking status of desired Homebrew formulae..."

    # List packages to be installed
    local -a missing_packages
    local -a desired_packages=(
        emmet
        minimap
        merge-conflicts
        color-picker
        linter
        linter-jshint
        linter-less
        linter-csslint
        linter-xmllint
        editorconfig
        xml-formatter
        solarized-dark-ui
        atom-beautify
        trailing-spaces
        sort-lines
        pretty-json
        highlight-line
        line-ending-converter
    )

    for index in ${!desired_packages[*]}
    do
        if ! apm_exists ${desired_packages[$index]}; then
            # Store the name (and options) of every missing package
            missing_packages=("${missing_packages[@]}" "${desired_packages[$index]}")
        fi
    done

    if [[ "$missing_packages" ]]; then
        # Install Atom packages
        e_header "Installing missing Atom packages..."
        apm install ${missing_packages[@]}

        [[ $? ]] && e_success "Done"
    fi

    # Cleanup
    apm clean
}
