#!/usr/bin/env bash

# Install applications using Homebrew Cask.
run_cask() {

    # Check for Homebrew
    if ! type_exists 'brew'; then
        e_error "Homebrew not installed, exiting..."
        exit
    fi

    # Adding more repos
    brew tap homebrew/cask-versions
    brew tap caskroom/fonts

    e_header "Checking status of desired Homebrew casks..."
    local list_apps
    local -a missing_apps
    local -a desired_apps=(
        azure-data-studio
        cyberduck
        docker
        dropbox
        firefox
        font-fira-code
        gitup
        google-chrome
        google-chrome-canary
        kdiff3
        microsoft-azure-storage-explorer
        opera
        postman
        skype
        slack
        the-unarchiver
        things
        visual-studio-code
        transmission
        vlc
        viscosity
    )

    for index in ${!desired_apps[*]}
    do
        if ! cask_exists ${desired_apps[$index]}; then
            # Store the name (and options) of every missing app
            missing_apps=("${missing_apps[@]}" "${desired_apps[$index]}")
        fi
    done

    if [[ "$missing_apps" ]]; then
        # Convert the array of missing apps into a list of space-separate strings
        list_apps=$( printf "%s " "${missing_apps[@]}" )

        # Hack to show the first-run brew-cask password prompt immediately.
        brew cask info this-is-somewhat-annoying 2>/dev/null

        e_header "Installing missing apps..."
        # Install all missing apps
        brew cask install --appdir="/Applications" $list_apps

        [[ $? ]] && e_success "Done"
    fi

    e_header "Cleans up cached cask downloads"
    brew cleanup

    [[ $? ]] && e_success "Done"
}
