#!/usr/bin/env bash

# Install applications using Homebrew Cask.
run_cask() {

    # Check for Homebrew
    if ! type_exists 'brew'; then
        e_error "Homebrew not installed, exiting..."
        exit
    fi

    # Exit if, for some reason, cask is not installed.
    if ! formula_exists 'brew-cask' ; then
        e_header "Installing Homebrew Cask..."
        brew install caskroom/cask/brew-cask
        [[ $? ]] && e_success "Done"
    fi

    # Adding more repos
    brew tap caskroom/versions

    e_header "Checking status of desired Homebrew casks..."
    local list_apps
    local -a missing_apps
    local -a desired_apps=(
        dropbox
        google-drive
        google-chrome
        firefox
        spotify
        sublime-text3
        skype
        kdiff3
        cyberduck
        sourcetree
        things
        webstorm
        ynab
        atom
    )

    for index in ${!desired_apps[*]}
    do
        if ! cask_exists ${desired_apps[$index]}; then
            # Store the name (and options) of every missing app
            missing_apps=("${missing_apps[@]}" "${desired_apps[$index]}")
        fi
    done

    if [[ "$missing_apps" ]]; then
        # Convert the array of missing apps into a list of space-separate strings
        list_apps=$( printf "%s " "${missing_apps[@]}" )

        # Hack to show the first-run brew-cask password prompt immediately.
        brew cask info this-is-somewhat-annoying 2>/dev/null

        e_header "Installing missing apps..."
        # Install all missing apps
        brew cask install --appdir="/Applications" $list_apps

        [[ $? ]] && e_success "Done"
    fi

	e_header "Cleans up cached cask downloads"
	brew cask cleanup

	[[ $? ]] && e_success "Done"
}
