#!/bin/bash

run_help() {

cat <<EOT
macOS dotfiles - Per Töyrä

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/pertoyra/dotfiles/

Licensed under the MIT license.
EOT

}
