#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Per Töyrä

Additional software to install

Browsers:
    Firefox
    Google Chrome
    Opera

Development:
    WebStorm
    Oxygen XML
    Xamarin
    SourceTree
    kdiff3
    IntelliJ IDEA CE
    Sublime Text
    Transmit
    Patterns
    SQLite Professional
    Xcode
    FontCustom

Productivity:
    Microsoft Office
    Things
    Day One
    BreakTime

Other:
    Dropbox
    Google Drive
    Skype
    Folder Watch
    Spotify
    CoRD
    BankID
    Moveslink
    rubiTrack
    YNAB

EOT

}
