#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Per Töyrä

Additional software to install

Development:
    Oxygen XML
    Transmit
    Patterns
    SQLite Professional
    Xcode

Productivity:
    Microsoft Office
    BreakTime

Other:
    BankID
    Moveslink
    rubiTrack
    YNAB

EOT

}
