#!/usr/bin/env bash

run_npm() {

    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
        local packages=(
            'http-server'
            'nodemon'
            'npm-check-updates'
        )

        # Configure global npm package folder
        GLOBAL_NODE_MODULES=~/.node_modules
        mkdir -p $GLOBAL_NODE_MODULES
        npm config set prefix $GLOBAL_NODE_MODULES

        # Install packages globally and quietly
        npm install ${packages[@]} --global --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
