#!/bin/bash

run_npm() {

    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
        local packages=(
            'http-server'
            'nodemon'
            'create-react-app'
            'eslint'
            'rimraf'
        )

        # Install packages globally and quietly
        sudo npm install ${packages[@]} --global --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
